### PR TITLE
support latest ansible version

### PR DESCRIPTION
**Pull request by dongwangdw**
Signed-off-by: dongdwdw <dongdwdw@cn.ibm.com>

### CODE REVIEW

**Comment by dongwangdw** [comment]
After ansible 2.10, there are some changes:
1. ansible-base renamed to ansible-core which is the minimal run time without any collection affliated by default.
2. ansible will be a community version with many utils collections in bundle.

I chose ansible although we got no dependency on other community collections now but it may be convenient if we need to expand features later.

About the changes:

1. Use the latest ansible version
2. User python3.9.
3. Change ansible-lint to ignore the warning "fqcn-builtins"
4. Update other dependencies to latest

**Comment by mbwhite** [comment]
@dongwangdw thank you for this.. appreciate it!

I was just thinking about migration here: anybody who is working with the current set of playbooks and upgrades the version of this collection will need to migrate to using a new version of ansible and also python 3.9?

Certainly, I think this might warrant a major version bump.

**Comment by dongwangdw** [comment]
> @dongwangdw thank you for this.. appreciate it!
> 
> I was just thinking about migration here: anybody who is working with the current set of playbooks and upgrades the version of this collection will need to migrate to using a new version of ansible and also python 3.9?

I have paused here a little too. Actually the least valid version is python 3.8 which is from [official doc](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#control-node-requirements).
I have tried to install the requirements.txt with python3.8 and it worked for the latest version.
But I still upgraded python. The latest python is 3.10 even 3.11. Looks like 3.8 is on the edge of deprecation. What is your prefer?
> 
> Certainly, I think this might warrant a major version bump.
OK. do you mean we can just bump it to v2.0.0? I thought this too. But let's agreen on this.

**Comment by mbwhite** [comment]
@dongwangdw I've updated the main branch to be marked as v2.0.0-beta. Would you able to 
1) rebase your PR on the latest main branch
2) update the `installation.rst` with the new versions of the dependencies
3) Add a note in the `migration.rst` document please?

And then we're good to merge!!  Thanks!

**Pull request closed without merging**
