### PR TITLE
fix type in dockerfile

### PR DESCRIPTION
**Pull request by alxiong**
Tried building the image locally, and fail. 

After fixing the typo, successfully build.

### CODE REVIEW

**Comment by sstone1** [comment]
@alxiong can you send me the log from `docker build` with the failure? I see a `.build` directory locally:

```
 ---> e9a21c750226
Step 13/21 : RUN cd /go/src/github.com/hyperledger/fabric     && make configtxlator peer GO_TAGS=pkcs11 EXECUTABLES=
 ---> Running in 36dd6bd7cb6d
.build/bin/configtxlator
CGO_CFLAGS=" " GOBIN=/go/src/github.com/hyperledger/fabric/.build/bin go install -tags "pkcs11" -ldflags "-X github.com/hyperledger/fabric/common/tools/configtxlator/metadata.CommitSHA=e0afaa741" github.com/hyperledger/fabric/common/tools/configtxlator
Binary available as .build/bin/configtxlator
.build/bin/peer
CGO_CFLAGS=" " GOBIN=/go/src/github.com/hyperledger/fabric/.build/bin go install -tags "pkcs11" -ldflags "-X github.com/hyperledger/fabric/common/metadata.Version=1.4.7 -X github.com/hyperledger/fabric/common/metadata.CommitSHA=e0afaa741 -X github.com/hyperledger/fabric/common/metadata.BaseVersion=0.4.20 -X github.com/hyperledger/fabric/common/metadata.BaseDockerLabel=org.hyperledger.fabric -X github.com/hyperledger/fabric/common/metadata.DockerNamespace=hyperledger -X github.com/hyperledger/fabric/common/metadata.BaseDockerNamespace=hyperledger" github.com/hyperledger/fabric/peer
Binary available as .build/bin/peer
Removing intermediate container 36dd6bd7cb6d
```

**Comment by alxiong** [comment]
here's the log:
```
Step 16/23 : COPY --from=builder /root/.ansible /root/.ansible
 ---> Using cache
 ---> 01a6af27eadb
Step 17/23 : COPY --from=fabric /go/src/github.com/hyperledger/fabric/.build/bin /opt/fabric/bin
COPY failed: stat /var/lib/docker/overlay2/7eec18740c2aaa26b1349081c6e36309c040db33ca4dc739882eebb4e3a0f779/merged/go/src/github.com/hyperledger/fabric/.build/bin: no such file or directory
```

**Comment by sstone1** [comment]
@alxiong can you send me the whole log with the cache turned off?

`docker build --no-cache -t ibmblockchain/ansible .`

Need to see the bits where it builds the Fabric binaries to see what is going on.

**Comment by alxiong** [comment]
right, here are the relevant logs -- it seems that the binaries are installed under `/build/` instead of `/.build/`:
```
Step 13/23 : RUN cd /go/src/github.com/hyperledger/fabric     && make configtxlator peer GO_TAGS=pkcs11 EXECUTABLES=
 ---> Running in 784e22fa3eb1
Building build/bin/configtxlator
GOBIN=/go/src/github.com/hyperledger/fabric/build/bin go install -tags "pkcs11" -ldflags "-X github.com/hyperledger/fabric/common/metadata.Version=2.1.1 -X github.com/hyperledger/fabric/common/metadata.CommitSHA=6393adbb2 -X github.com/hyperledger/fabric/common/metadata.BaseDockerLabel=org.hyperledger.fabric -X github.com/hyperledger/fabric/common/metadata.DockerNamespace=hyperledger" github.com/hyperledger/fabric/cmd/configtxlator
Building build/bin/peer
GOBIN=/go/src/github.com/hyperledger/fabric/build/bin go install -tags "pkcs11" -ldflags "-X github.com/hyperledger/fabric/common/metadata.Version=2.1.1 -X github.com/hyperledger/fabric/common/metadata.CommitSHA=6393adbb2 -X github.com/hyperledger/fabric/common/metadata.BaseDockerLabel=org.hyperledger.fabric -X github.com/hyperledger/fabric/common/metadata.DockerNamespace=hyperledger" github.com/hyperledger/fabric/cmd/peer
Removing intermediate container 784e22fa3eb1
 ---> 2984b053873d
Step 14/23 : FROM registry.access.redhat.com/ubi8/ubi-minimal
 ---> c58d4cf08dc2
Step 15/23 : COPY --from=builder /root/.local /root/.local
```

here's the dockerfile:
Screenshot 2020-07-14 at 6 26 21 PM

**Comment by sstone1** [comment]
@alxiong ahh, you're using the v2.1.1 version of Fabric instead of v1.4.7, was that a change you made? I guess the build process for Fabric changed between v1.4 and v2.x.

**Comment by alxiong** [comment]
ah!! yes, I forget that I changed that!

Alright then, I guess we can close the issue now.

**Comment by sstone1** [comment]
Cool, I'll remember when we upgrade the binaries that we need to change that as well!

**Pull request closed without merging**
